INTERFACE /esrcc/if_const_msg
  PUBLIC.

  CONSTANTS abort   TYPE c LENGTH 1 VALUE 'A' ##NO_TEXT.
  CONSTANTS error   TYPE c LENGTH 1 VALUE 'E' ##NO_TEXT.
  CONSTANTS exit    TYPE c LENGTH 1 VALUE 'X' ##NO_TEXT.
  CONSTANTS info    TYPE c LENGTH 1 VALUE 'I' ##NO_TEXT.
  CONSTANTS success TYPE c LENGTH 1 VALUE 'S' ##NO_TEXT.
  CONSTANTS warning TYPE c LENGTH 1 VALUE 'W' ##NO_TEXT.

ENDINTERFACE.
